apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-bai-operator-catalog-subscription
  namespace: REPLACE_NAMESPACE
spec:
  channel: v24.1
  name: ibm-bai-insights-engine-operator
  installPlanApproval: Automatic
  source: ibm-bai-operator-catalog
  sourceNamespace: openshift-marketplace
