###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-bai-operator
  labels:
    app.kubernetes.io/instance: ibm-bai
    app.kubernetes.io/managed-by: ibm-bai
    app.kubernetes.io/name: ibm-bai
    release: 24.0.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-bai-operator
subjects:
- kind: ServiceAccount
  name: ibm-bai-insights-engine-operator
  namespace: <NAMESPACE>
